app/Models/ParkingPlaces.php, database/migrations/2024_06_06_125605_create_parking_places_table.php, database/seeders/DatabaseSeeder.php, database/seeders/parking_placesTableSeeder.php
Additions:
- parking_places_table.php
- ParkingPlaces.php for model
- parking_placesTableSeeder.php
Changes:
- DatabaseSeeder.php
- to run parking_placesTableSeeder
=> [migrations/parking_places_table]

resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
- Update register UI form
- Update register.php
[UI/login]
- Update login UI form
- Update login.php
=> [UI/register]

app/Http/Controllers/Auth/RegisterController.php, app/Models/User.php, routes/web.php
Updated - change the default column's name 'name' to 'username'
- RegisterController
- Model/User.php
- Route/web.php
=> [Backend/register]

database/migrations/2024_06_05_154224_create_prices_table.php, database/migrations/2024_06_05_154601_create_favorites_table.php, resources/views/auth/register.blade.php
< Additons >
migration/create_prices_table
migration/create_favorites_table
< Modifying class names >
register.blade.php
btn → btn-r
=> prices_table,favorites_table

app/Http/Controllers/FavoriteController.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/ParkingPlaceController.php, app/Http/Controllers/ReviewController.php, app/Models/ParkingPlace.php, app/Models/Review.php, database/seeders/DatabaseSeeder.php, database/seeders/ReviewSeeder.php, public/css/style.css, resources/views/Parking_lots/parking_detail.blade.php, resources/views/auth/login_to_favorite.blade.php, resources/views/home.blade.php, routes/web.php
Additions:
- ParkingPlaceController.php
- ReviewController.php
- ReviewSeeder.php
- login_to_favorite.php
Changes:
- updated DatabaseSeeder.php
- to run ReviewSeeder
- updated HomeController.php
- changed the routes to navigate to another page
- updated home.php
- fixed the favorite part and price part
- updated FavoriteController.php, model of ParkingPlace and Review, style.css, parking_detail.php and web.php
- created routes and made each button correspond to a transition to the next page or store the data
=> [Backend/parking_detail]

public/css/style.css, resources/views/user_info/favorite.blade.php
Changes:
- fixed style.css
- class name is not informative so changed the name
- updated favorite.php
=> [UI/favorite list]

app/Http/Controllers/Auth/RegisterController.php, public/css/style.css, resources/views/auth/login.blade.php, resources/views/user_info/profile.blade.php, resources/views/user_info/reservation.blade.php
- Fix some error
- Move all css to style.css file
=> [UI / login, profile, reservation]

app/Http/Controllers/Admin/UsersController.php, app/Http/Middleware/AdminMiddleware.php, app/Models/User.php, public/css/style.css, routes/web.php
Additions
view/admin/index.blade.php
route of Admin
=> [UI/register_new_parking]

public/css/style.css, resources/views/Parking_lots/models/Reservation_check.blade.php, resources/views/Parking_lots/reservation.blade.php
Additions:
-Added Reservation_check.blade file
=> [UI/reservation_check]reservation Check UI

app/Http/Controllers/ReservationsController.php, resources/views/Parking_lots/models/Reservation_check.blade.php, resources/views/Parking_lots/reservation.blade.php, routes/web.php
Additions:
- show the reservation information in the reservation check modal
=> [Backend/reservation_check]-reservation-check

public/css/style.css, resources/views/admin/users/users_list.blade.php
Additional
- create user list table
=> [UI / Admin user list]

public/css/style.css, resources/views/Parking_lots/parking_detail.blade.php, resources/views/parking_lots/parking_list.blade.php, routes/web.php
Changes:
- Updated parking_lisy.php and style.css
- created a filter search bar that is opened when you click filter button
- Updated parking_detail.php
- fixed UI
=> [UI/parking_list_filter_search]

app/Http/Controllers/Admin/UsersController.php, app/Models/User.php, public/css/style.css, resources/views/admin/users/users_list.blade.php, routes/web.php
Additional
- set up Delete(deactivate user) / Restore(activate user) button
- create some function and route for delete / restore users
- add softDelete to Model  "User.php"
=> [ Backend / Admin user list ]

public/css/style.css, resources/views/user_info/reservation.blade.php, routes/web.php
Additions:
add Reservation History page
=> [UI / ReservationHistory]

app/Http/Controllers/Auth/RegisterController.php, public/css/style.css, resources/views/auth/register.blade.php
- add function in RegisterController to show the modal of success message
- add javascript and modal code in register.blade.php
- add css
=> [Backend / Register]

app/Http/Controllers/Admin/AdminParkingController.php, app/Http/Controllers/Admin/UsersController.php, resources/views/admin/parking/parkings_list.blade.php, resources/views/admin/users/users_list.blade.php, routes/web.php
=> [backend/admin_parking_list]

resources/views/layouts/app.blade.php
=> [backend/navbar_footer_sidebar]

app/Http/Controllers/HomeController.php, public/css/style.css, resources/views/faq.blade.php, routes/web.php
- create file "faq.blade.php"
- create function in HomeController
- create Route in web.php
- add css
=> [UI / FAQ]

resources/views/layouts/app.blade.php
- add route of FAQ to each bar
=> [Backend / nav bar and side bar]

app/Http/Controllers/HomeController.php, resources/views/home.blade.php
Changes:
- Updated HomeController.php and home.php
- fixed the order of recommendations
=> [Backend/home]

resources/views/admin/parking/index.blade.php
=> [ UI / register new parking ]

app/Http/Controllers/Admin/AdminParkingController.php, resources/views/admin/parking/index.blade.php, resources/views/admin/parking/parking_detail.blade.php, resources/views/admin/parking/parkings_list.blade.php, resources/views/admin/parking/update_parking.blade.php, routes/web.php
Additions:
back button
route of updateParking
route of edit
route of show
admin/parking/parking_detail.blade.php
=> [backend/update_parking_place]

resources/views/Parking_lots/parking_detail.blade.php, resources/views/admin/users/users_list.blade.php, resources/views/auth/register.blade.php, resources/views/layouts/app.blade.php, resources/views/user_info/profile.blade.php
Changes:
- Updated parking_detail.php
- Added a title and fixed UI
- Updated users_list.php, register.php, app.php and profile.php
- Refactored the code and fixed UI
=> [Backend/parking_detail_v2]

app/Http/Controllers/ParkingPlaceController.php, app/Http/Controllers/ReservationsController.php, app/Models/ParkingPlace.php, database/migrations/2024_06_06_125605_create_parking_places_table.php, resources/views/admin/parking/index.blade.php, resources/views/admin/parking/parkings_list.blade.php, resources/views/layouts/app.blade.php, resources/views/parking_lots/parking_list.blade.php
Changes:
- Updated ParkingPlaceController.php, model of ParkingPlace and parking_list.php
- made the filter search work (it's not completed but I want to update it at this point)
- Updated parking_places_table and index.php for admin
- changed  maximum_amount field to be nullable
- Updated ReservationController.php, parkings_list.php for admin and app.php
- fixed small things
=> [Backend/parking_list_filter_search_v2]

app/Http/Controllers/ParkingPlaceController.php, app/Http/Controllers/ReviewController.php, resources/views/Parking_lots/parking_detail.blade.php, resources/views/user_info/reservation.blade.php, routes/web.php
-- it cannot be written review to cancel reservation. -- it is possible to delete own review
=> Change specifications

app/Http/Controllers/ProfileController.php
-- Modify to prepare an array of reviews only for past reservations.
=> fix-review

app/Http/Controllers/Admin/UsersController.php, resources/views/auth/register.blade.php, resources/views/user_info/profile.blade.php, resources/views/user_info/reservation.blade.php
- fix small bugs in register.blade.php
- change small parts of function in admin UserController
- change tab's name in user profile page and reservation history page
=> [ Testing ]

resources/views/user_info/reservation.blade.php
-- fix how to display time
10:00:00⇒10:00
=> [fix-current_reservation]

public/css/style.css, resources/views/user_info/favorite.blade.php, resources/views/user_info/profile.blade.php, resources/views/user_info/reservation.blade.php
Adjust user information page's UI to the responsive design
- Profile
- Favorites
- Reservation History
Add some custom css
=> [ UI / responsive design ]

public/css/style.css, resources/views/Parking_lots/parking_detail.blade.php, resources/views/admin/parking/index.blade.php, resources/views/home.blade.php, resources/views/layouts/app.blade.php, resources/views/parking_lots/parking_list.blade.php, resources/views/user_info/favorite.blade.php, resources/views/user_info/update_profile.blade.php
Changes:
- Updated style.css, home.php, parking_list.php, parking_detail.php and favorite.php
- made all pages responsive
- Updated admin_paking_list and app.php
- fixed small mistakes
=> [UI/Responsive_design]

resources/views/auth/register.blade.php, routes/web.php
=> [ Backend / register page ]

resources/views/Parking_lots/parking_detail.blade.php
Changes:
- Updated parking_detail.php
- fixed bug
=> [UI/parking_detail]
